source /Users/nobu/.git-completion.bash
source /Users/nobu/.git-prompt.sh

export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
alias vi='/usr/local/bin/vim'
alias ll='ls -l'
alias done='pb yo'

export GIT_PS1_SHOWDIRTYSTATE=1
# prompt with git branch name in purple color
# export PS1='\w$(__git_ps1 " (\e[0;35m%s\e[m)")\$ '
export PS1='\w\$ '

export PATH="$HOME/.rbenv/bin:$HOME/.composer/vendor/bin:$PATH"
eval "$(rbenv init -)"
