" colorscheme midnight2
set background=dark
colorscheme solarized
" set gfn=DejaVu\ Sans\ Mono:h14
" set gfn=Source\ Code\ Pro\ Medium:h16
set gfn=Monaco:h14
set columns=120
set lines=80
set linespace=3
set guioptions-=T
set guioptions+=b
