" https://github.com/square/maximum-awesome
"
set shell=/bin/bash
set nocompatible

call plug#begin('~/.vim/plugged')

Plug 'kchmck/vim-coffee-script'
Plug 'ton/vim-bufsurf'
Plug 'hail2u/vim-css3-syntax'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-markdown'
Plug 'PProvost/vim-markdown-jekyll'
Plug 'kien/ctrlp.vim'
Plug 'jasoncodes/ctrlp-modified.vim'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'rking/ag.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise'
Plug 'slim-template/vim-slim'
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-fugitive'
Plug 'spf13/vim-autoclose'
Plug 'scrooloose/nerdtree'
Plug 'pangloss/vim-javascript'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'tpope/vim-repeat'
Plug 'mustache/vim-mustache-handlebars'
Plug 'tpope/vim-haml'
Plug 'terryma/vim-expand-region'
Plug 'sjl/gundo.vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'whatyouhide/vim-gotham'
Plug 'rhysd/clever-f.vim'
Plug 'junegunn/vim-easy-align'
Plug 'ivalkeen/vim-simpledb'
Plug 'hhvm/vim-hack'

call plug#end()


set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc
set autoread
set enc=utf-8
set fenc=utf-8
set iminsert=0 imsearch=0
set showcmd
set incsearch
"set nocompatible
set hlsearch
set hidden
set expandtab
set ts=2 sw=2 sts=2
set fo+=r
set shortmess+=I
set cindent
set ignorecase
set smartcase
set backspace=2
set wrapscan
set showmatch
set wildmenu
set formatoptions+=mM
set number
set ruler
set nolist
set wrap
set laststatus=2
set cmdheight=1
set title
set shortmess+=I
set nobackup
set dir=~/.vim/swap/
set vb t_vb=
set clipboard=unnamed
set synmaxcol=150
" set lazyredraw
syn on
" XXX are these working?
let g:rubycomplete_buffer_loading = 1
let g:rubycomplete_classes_in_global = 1
let g:rubycomplete_rails = 1
set tags+=gems.tags
set mouse=a

let mapleader = ' '

" nnoremap <C-h> :BufSurfBack<CR>
" nnoremap <C-l> :BufSurfForward<CR>
" nnoremap <C-g> :Ack 
" nnoremap <C-b> :RunSpec<cr>

nmap ; :
"nnoremap : ;
noremap ;; ;

"imap jj <ESC>
imap <C-d> <DEL>
imap <C-e> <END>
imap <C-a> <HOME>
imap <C-k> <ESC><RIGHT>C
imap <C-[> <ESC>lv$hS)

"imap ,/ </<C-X><C-O><ESC>F<i
"inoremap \[ [
"inoremap \{ {
"inoremap \( (
"inoremap \" "
"inoremap \' '
"inoremap [ []<LEFT>
"inoremap { {}<LEFT><CR><ESC>O
"inoremap ( ()<LEFT>
"inoremap " ""<LEFT>
"inoremap ' ''<LEFT>

"let g:syntastic_ruby_exec = '/Users/nobu/.rvm/rubies/ruby-1.9.3-p448/bin/ruby'

" augroup reload_vimrc " {
"     autocmd!
"     autocmd BufWritePost $MYVIMRC source $MYVIMRC
" augroup END " }

" autocmd BufReadPost,FileReadPost,BufNewFile * call system("tmux rename-window " . expand("%:t"))
"autocmd BufNewFile,BufRead ~/work/qdopp/* set tabstop=4 shiftwidth=4
" let g:ackprg = 'ag --nogroup --nocolor --column'

nmap <leader>a :Ag<space>
nmap <leader>d :NERDTreeToggle<CR>
nmap <leader>t :CtrlP<CR>
nmap <leader>T :CtrlPClearCache<CR>:CtrlP<CR>
nmap <leader>c :ccl<CR>
nmap <leader>p :set paste<CR>
nmap <leader>P :set nopaste<CR>
nmap <leader><space> :noh<CR>
nmap <leader>u :GundoToggle<CR>
nmap <leader>ga :Git add --all .<CR><CR>
nmap <leader>gs :Gstatus<CR>
nmap <leader>gc :Git add --all .<CR><CR>:Gcommit -a<CR>
nmap <leader>h :BufSurfBack<CR>
nmap <leader>l :BufSurfForward<CR>
nmap <leader>m :CtrlPModified<CR>
nmap <leader>fa :CtrlP app/assets<CR>
nmap <leader>fm :CtrlP app/models<CR>
nmap <leader>fc :CtrlP app/controllers<CR>
nmap <leader>fv :CtrlP app/views<CR>
nmap <leader>w :w<CR>
nmap <leader>- <C-w>s
nmap <leader>\ <C-w>v

let g:ctrlp_working_path_mode = 0

if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif

" hi IndentGuidesOdd  ctermbg=gray
" hi IndentGuidesEven ctermbg=none
hi Pmenu ctermbg=gray ctermfg=black
hi PmenuSel ctermbg=blue ctermfg=white

" let g:airline#extensions#tabline#enabled = 1

" noremap <C-h> <C-w>h
" noremap <C-j> <C-w>j
" noremap <C-k> <C-w>k
" noremap <C-l> <C-w>l
noremap <C-c> <C-w>c

vmap <Enter> <Plug>(EasyAlign)
" nmap <Leader>a <Plug>(EasyAlign)
