set enc=utf-8
set fenc=utf-8
set iminsert=0 imsearch=0
set showcmd
set incsearch
set nocompatible
set hlsearch
set hidden
set expandtab
set ts=2 sw=2 sts=2
"set clipboard+=unnamed
set fo+=r
set shortmess+=I
set cindent
set ignorecase
set smartcase
set backspace=2
set wrapscan
set showmatch
set wildmenu
set formatoptions+=mM
set number
set ruler
set nolist
set wrap
set laststatus=2
set cmdheight=2
set title
set shortmess+=I
set nobackup
set dir=~/.vim/swap/
set vb t_vb=
syn on

nnoremap <C-h> :BufSurfBack<CR>
nnoremap <C-l> :BufSurfForward<CR>

nnoremap ; :
nnoremap : ;

imap jj <ESC>
imap <C-d> <DEL>
imap <C-e> <END>
imap <C-a> <HOME>
imap <C-k> <ESC><RIGHT>C

imap ,/ </<C-X><C-O><ESC>F<i
inoremap \[ [
inoremap \{ {
inoremap \( (
inoremap \" "
inoremap \' '
inoremap [ []<LEFT>
inoremap { {}<LEFT><CR><ESC>O
inoremap ( ()<LEFT>
inoremap " ""<LEFT>
inoremap ' ''<LEFT>

set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'
Bundle 'paulyg/Vim-PHP-Stuff'
Bundle 'tobiassvn/vim-gemfile'
Bundle 'kchmck/vim-coffee-script'
Bundle 'beyondwords/vim-twig'
Bundle 'ton/vim-bufsurf'
Bundle 'altercation/vim-colors-solarized'
Bundle 'hail2u/vim-css3-syntax'
Bundle 'cakebaker/scss-syntax.vim'
Bundle 'tpope/vim-rails'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-markdown'
Bundle 'PProvost/vim-markdown-jekyll'
Bundle 'kien/ctrlp.vim'
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
Bundle "garbas/vim-snipmate"
Bundle "honza/vim-snippets"
Bundle 'Lokaltog/vim-easymotion'
Bundle 'scrooloose/syntastic'
Bundle 'mileszs/ack.vim'

filetype plugin indent on

let g:syntastic_ruby_exec = '/Users/nobu/.rvm/rubies/ruby-1.9.2-p320/bin/ruby'

augroup reload_vimrc " {
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }
